//! Assets compiled into the `actime` binary.
//!
//! Policy packs, profiles, and the demo agent ship inside the executable so a
//! single downloaded binary is fully functional with nothing else on disk.

/// A policy pack shipped with Actime.
pub struct Pack {
    /// Pack id, as used in `policy.packs` in `actime.yaml`.
    pub name: &'static str,
    /// One-line description shown by `actime policy list`.
    pub summary: &'static str,
    /// The ActPlane DSL source, before `${WORKSPACE}` substitution.
    pub source: &'static str,
}

/// Every policy pack shipped with Actime, in the order `policy list` prints them.
pub const PACKS: &[Pack] = &[
    Pack {
        name: "coding-agent-baseline",
        summary: "System fence, evidence integrity, credential reporting, destructive VCS and mass deletion",
        source: include_str!("../../../policies/coding-agent-baseline.dsl"),
    },
    Pack {
        name: "no-vcs-write",
        summary: "The agent edits the working tree; commits and pushes stay a human decision",
        source: include_str!("../../../policies/no-vcs-write.dsl"),
    },
    Pack {
        name: "no-secret-egress",
        summary: "Data derived from secret files may not reach the network, however it is copied",
        source: include_str!("../../../policies/no-secret-egress.dsl"),
    },
];

/// The built-in profiles, as YAML, keyed by name.
pub const PROFILES: &[(&str, &str)] = &[
    ("observe", include_str!("../../../profiles/observe.yaml")),
    ("balanced", include_str!("../../../profiles/balanced.yaml")),
    ("strict", include_str!("../../../profiles/strict.yaml")),
];

/// The stand-in agent used by `actime demo`.
pub const DEMO_AGENT: &str = include_str!("../../../examples/demo-agent.sh");

/// Look up a policy pack by name.
pub fn pack(name: &str) -> Option<&'static Pack> {
    PACKS.iter().find(|p| p.name == name)
}

/// Look up a built-in profile's YAML by name.
pub fn profile(name: &str) -> Option<&'static str> {
    PROFILES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, yaml)| *yaml)
}

/// Render the named packs and any extra policy files into one DSL document,
/// substituting `${WORKSPACE}` with the workspace path the agent will see.
///
/// Returns an error naming the unknown pack if one is not found.
pub fn compose_policy(
    packs: &[String],
    extra_sources: &[(String, String)],
    workspace: &str,
) -> anyhow::Result<String> {
    let mut out = String::new();
    out.push_str("# Generated by actime. Do not edit; edit actime.yaml instead.\n");
    out.push_str(&format!("# workspace = {workspace}\n"));

    for name in packs {
        let p = pack(name).ok_or_else(|| {
            anyhow::anyhow!(
                "unknown policy pack `{name}`. Known packs: {}",
                PACKS.iter().map(|p| p.name).collect::<Vec<_>>().join(", ")
            )
        })?;
        out.push_str(&format!("\n# ---- pack: {} ----\n", p.name));
        out.push_str(&p.source.replace("${WORKSPACE}", workspace));
    }

    for (path, source) in extra_sources {
        out.push_str(&format!("\n# ---- file: {path} ----\n"));
        out.push_str(&source.replace("${WORKSPACE}", workspace));
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_pack_is_non_empty_and_named() {
        assert_eq!(PACKS.len(), 3);
        for p in PACKS {
            assert!(!p.name.is_empty());
            assert!(!p.summary.is_empty());
            assert!(p.source.contains("rule "), "{} has no rules", p.name);
        }
    }

    #[test]
    fn every_profile_parses_as_yaml() {
        for (name, yaml) in PROFILES {
            let v: serde_yaml::Value =
                serde_yaml::from_str(yaml).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert!(v.get("version").is_some(), "{name} has no version");
        }
    }

    #[test]
    fn compose_substitutes_workspace_everywhere() {
        let dsl = compose_policy(
            &["coding-agent-baseline".into(), "no-vcs-write".into()],
            &[],
            "/srv/project",
        )
        .expect("compose");
        assert!(!dsl.contains("${WORKSPACE}"));
        assert!(dsl.contains("/srv/project"));
        assert!(dsl.contains("pack: coding-agent-baseline"));
        assert!(dsl.contains("pack: no-vcs-write"));
    }

    #[test]
    fn compose_substitutes_in_extra_files_too() {
        let extra = vec![(
            "team.dsl".to_string(),
            "rule x:\n  notify write file \"${WORKSPACE}/**\" if AGENT\n".to_string(),
        )];
        let dsl = compose_policy(&[], &extra, "/srv/project").expect("compose");
        assert!(!dsl.contains("${WORKSPACE}"));
        assert!(dsl.contains("/srv/project/**"));
    }

    #[test]
    fn unknown_pack_names_the_known_ones() {
        let err = compose_policy(&["nope".into()], &[], "/w")
            .unwrap_err()
            .to_string();
        assert!(err.contains("nope"));
        assert!(err.contains("coding-agent-baseline"));
    }

    #[test]
    fn demo_agent_is_a_shell_script_that_triggers_a_rule() {
        assert!(DEMO_AGENT.starts_with("#!/bin/sh"));
        // The demo must exercise the baseline pack's destructive-vcs rule.
        assert!(DEMO_AGENT.contains("git push --force"));
    }

    #[test]
    fn lookup_helpers() {
        assert!(pack("no-secret-egress").is_some());
        assert!(pack("does-not-exist").is_none());
        assert!(profile("balanced").is_some());
        assert!(profile("paranoid").is_none());
    }
}
