//! Assets compiled into the `actime` binary.
//!
//! Policy packs and profiles ship inside the executable so a single downloaded
//! binary is fully functional with nothing else on disk.

/// A policy pack shipped with Actime.
pub struct Pack {
    /// Pack id, as used in `policy.packs` in `actime.yaml`.
    pub name: &'static str,
    /// One-line description shown by `actime policy list`.
    pub summary: &'static str,
    /// The ActPlane DSL source, before `${WORKSPACE}` substitution.
    pub source: &'static str,
}

/// Every policy pack shipped with Actime, in the order `policy list` prints them.
pub const PACKS: &[Pack] = &[
    Pack {
        name: "coding-agent-baseline",
        summary: "Destructive VCS and mass deletion (exec rules that install on ActPlane 0.1.8)",
        source: include_str!("../../../policies/coding-agent-baseline.dsl"),
    },
    Pack {
        name: "no-vcs-write",
        summary: "The agent edits the working tree; commits and pushes stay a human decision",
        source: include_str!("../../../policies/no-vcs-write.dsl"),
    },
    Pack {
        name: "information-flow",
        summary: "File fences, credential reporting, secret-egress labels (needs engine file-sink features)",
        source: include_str!("../../../policies/information-flow.dsl"),
    },
];

/// The built-in profiles, as YAML, keyed by name.
pub const PROFILES: &[(&str, &str)] = &[
    ("observe", include_str!("../../../profiles/observe.yaml")),
    ("balanced", include_str!("../../../profiles/balanced.yaml")),
    ("strict", include_str!("../../../profiles/strict.yaml")),
];

/// Look up a policy pack by name.
pub fn pack(name: &str) -> Option<&'static Pack> {
    PACKS.iter().find(|p| p.name == name)
}

/// Look up a built-in profile's YAML by name.
pub fn profile(name: &str) -> Option<&'static str> {
    PROFILES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, yaml)| *yaml)
}

/// Render the named packs and any extra policy files into one DSL document,
/// substituting `${WORKSPACE}` with the workspace path the agent will see.
///
/// Returns an error naming the unknown pack if one is not found.
pub fn compose_policy(
    packs: &[String],
    extra_sources: &[(String, String)],
    workspace: &str,
) -> anyhow::Result<String> {
    let mut out = String::new();
    out.push_str("# Generated by actime. Do not edit; edit actime.yaml instead.\n");
    out.push_str(&format!("# workspace = {workspace}\n"));

    for name in packs {
        let p = pack(name).ok_or_else(|| {
            anyhow::anyhow!(
                "unknown policy pack `{name}`. Known packs: {}",
                PACKS.iter().map(|p| p.name).collect::<Vec<_>>().join(", ")
            )
        })?;
        out.push_str(&format!("\n# ---- pack: {} ----\n", p.name));
        out.push_str(&p.source.replace("${WORKSPACE}", workspace));
    }

    for (label, source) in extra_sources {
        out.push_str(&format!("\n# ---- file: {label} ----\n"));
        out.push_str(&source.replace("${WORKSPACE}", workspace));
        if !source.ends_with('\n') {
            out.push('\n');
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_pack_has_rules() {
        for p in PACKS {
            assert!(
                p.source
                    .lines()
                    .any(|l| l.trim_start().starts_with("rule ")),
                "pack {} has no rules",
                p.name
            );
        }
    }

    #[test]
    fn compose_substitutes_workspace() {
        let packs = vec!["coding-agent-baseline".into()];
        let dsl = compose_policy(&packs, &[], "/tmp/ws").expect("compose");
        assert!(dsl.contains("/tmp/ws"));
        assert!(!dsl.contains("${WORKSPACE}"));
    }

    #[test]
    fn unknown_pack_is_named() {
        let err = compose_policy(&["nope".into()], &[], "/w")
            .unwrap_err()
            .to_string();
        assert!(err.contains("nope"));
    }

    #[test]
    fn profiles_are_loadable() {
        for name in ["observe", "balanced", "strict"] {
            assert!(profile(name).is_some(), "missing profile {name}");
            assert!(!profile(name).unwrap().contains("sandbox"));
        }
    }
}
